### ISSUE TITLE
Name Conflict from Xcode 15

### ISSUE THREAD

**Issue by JCSooHwanCho** [ReactiveX/RxSwift#2532]
**Short description of the issue**:
Since introduction of Observation framework, importing both RxSwift and Observation arises name conflict

**Expected outcome**:

compile without error

**What actually happens**:

compile error

```
Protocol 'Observable' does not have primary associated types that can be constrained
```

**Self contained code example that reproduces the issue**:

```swift
import SwiftUI
import RxSwift

struct ContentView: View {
    var body: some View {
        Color.black
    }

    func observable() -> Observable<Int> { // Protocol 'Observable' does not have primary associated types that can be constrained
        .just(1)
    }
}
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

6.6.0

**Platform/Environment**

  - [x] iOS
  - [x] macOS
  - [x] tvOS
  - [x] watchOS
  - [x] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Xcode 15 developer beta 2
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Swift Package Manager

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by 0xpablo** [comment]
A workaround to this issue is to declare a `typealias` of Observable inside the modules you are experiencing issues: 

```swift
import RxSwift

// Needed to disambiguate between Foundation's Observable and RxSwift's Observable
public typealias Observable = RxSwift.Observable
```

**Comment by freak4pc** [comment]
As @0xpablo suggested, this should be solved in the next beta seed hopefully.
Thanks for flagging this!
https://github.com/apple/swift/pull/66367

**Comment by JCSooHwanCho** [comment]
Is that PR really solves this issue? It just seems ensuring success resolution of macro code, not my code. As long as Observable protocol declaration is public, this problem will be persited, I think.

**Comment by freak4pc** [comment]
@JCSooHwanCho I'm unsure as well. I tried the latest dev snapshot and it doesn't solve it :( 
I'm continuing the discussion here:
https://forums.swift.org/t/pitch-observation-revised/63757/101

**Comment by freak4pc** [comment]
I just tested the last nightly seed (Jul 2) of Swift 5.9 and it seems the problem is fixed!
Exciting :) I hope this will be released in an upcoming beta soon.

**Comment by JCSooHwanCho** [comment]
@freak4pc I found the PR that solves this issue. It resolves by lowering priority of name look-up of standard library.

It doesn't seems the true solution though, it can allow us more time react for language evolution.

BTW, I have a curiosity about is there any plan renaming to resolve this issue. can you let me know about it?

**Comment by freak4pc** [comment]
I don't think we will make any renames, this is against what we want to achieve with the project here, and I really don't consider it this project's problem that Apple decided to cause havoc 😅 

What we can do is expose a `public typealias RxObservable = RxSwift.Observable` in the repo so folks can use RxObservable and Observable if they need the observability framework, which might help in that specific scenario. 

Also note that I'm pretty sure people will be able to use `Observability.Observable` if they need it, at the worst case.

**Comment by freak4pc** [comment]
I just installed Xcode 15 Beta 3 and the problem is still not solved in our main app /: very strange.

**Comment by freak4pc** [comment]
Here's what I did for now:

1. I have a new branch on the RxSwift called `alias`, it introduces a new RxObservable alias.
2. In my main project, I did a find and replace for the following regex: 

<img width="363" alt="image" src="https://github.com/ReactiveX/RxSwift/assets/605076/254c6f12-1d39-4e1a-b90d-baa2589aae49">

My project builds now. It's not really a super great solution, but it's reasonable for the time being (much more reasonable than an entire rename).

**Comment by oryonatan** [comment]
> 

Not fixed in Xcode 15 Beta 4.

**Comment by oryonatan** [comment]
> I just installed Xcode 15 Beta 3 and the problem is still not solved in our main app /: very strange.
Not fixed in Beta 4 either.

**Comment by freak4pc** [comment]
@oryonatan Mind trying the fix I suggested above? It seems to have solved it for the meanwhile for several projects.

**Comment by JCSooHwanCho** [comment]
It seems resolved in Xcode 15 beta 5.

**Comment by freak4pc** [comment]
That's interesting, the protocol is still there. 
For our huge codebase it also seems to work, but I had to `import RxSwift` in a single file where just doing `import RxCocoa` wasn't enough for some reason.

**Comment by freak4pc** [comment]
I'm closing this thread for now, seems like indeed this is fixed. If anything changes, feel free to comment here.

**Comment by JCSooHwanCho** [comment]
https://github.com/apple/swift/issues/67815

I opened an issue about it

**Comment by nikolaykasyanov** [comment]
I'm not sure if it's the same issue that's partially back or a new one in beta 6.

It's not as bad as the original one, though, as it only happens in contexts like this:

```swift
private extension Observable where Element == Error {
    func doStuff() -> Observable<Void> {
            flatMap { _ -> Observable<Void> in
                let completable = Completable.empty()

                return completable.andThen(Observable.just(Void()))
            }
    }
}
```

Please note that I don't even have a SwiftUI/Observation import in this file. Prefixing `Observable.just` with `RxSwift.` helps.

**Comment by awBSH** [comment]
issue still reproducible with `Xcode 15.0 Beta 7`
![Screenshot 2023-08-23 at 14 01 15](https://github.com/ReactiveX/RxSwift/assets/10061747/7a6c61b3-d7c4-4bef-9440-0b93b15e6458)

**Comment by arctouch-mateusbrigido** [comment]
Issue seems to be gone in `Xcode 15.0 beta 8`. Anyone else can confirm?

**Comment by oryonatan** [comment]
still an issue in beta 8 for me.

**Comment by freak4pc** [comment]
Apple core team suggests this PR will resolve the issue in an upcoming beta:
https://github.com/apple/swift/pull/68254

See discussion:
https://github.com/apple/swift/issues/67815#issuecomment-1701944076

**Comment by kaurprabhjeet** [comment]
Hi team I am getting this issue In Xcode 15.0.1 Using pod 'RxSwiftExt', '~> 5' 
<img width="1329" alt="Screenshot 2023-11-24 at 11 36 44 PM" src="https://github.com/ReactiveX/RxSwift/assets/132692604/1817fc2a-ba12-4cb4-985e-951cd7de7d0a">
Can someone guide me here which approach I should follow?
Thanks.
